2018-11-04 14:39:00,845 ERROR: Exception on /_response_email [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 251, in response_email
    send_response_email(email=recip,template=template)
  File "/Users/timc/PycharmProjects/SAAC/app/email.py", line 51, in send_response_email
    mail.send(msg)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: cannot unpack non-iterable NoneType object
2018-11-04 14:39:14,473 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:39:21,401 ERROR: Exception on /_response_email [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 251, in response_email
    send_response_email(email=recip,template=template)
  File "/Users/timc/PycharmProjects/SAAC/app/email.py", line 51, in send_response_email
    mail.send(msg)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: cannot unpack non-iterable NoneType object
2018-11-04 14:43:10,387 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:43:19,297 ERROR: Exception on /_response_email [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 251, in response_email
    send_response_email(email=recip,template=template)
  File "/Users/timc/PycharmProjects/SAAC/app/email.py", line 51, in send_response_email
    mail.send(msg)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: cannot unpack non-iterable NoneType object
2018-11-04 14:44:47,187 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:46:27,554 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:48:42,637 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:50:03,112 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:50:31,957 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:51:37,352 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-04 14:51:48,990 ERROR: Exception on /_response_email [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 251, in response_email
    send_response_email(email=recip,template=template)
  File "/Users/timc/PycharmProjects/SAAC/app/email.py", line 51, in send_response_email
    mail.send(msg)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'': (555, b'5.5.2 Syntax error. e4sm9885421qka.31 - gsmtp')}
2018-11-04 14:52:25,063 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
