2018-11-04 14:52:32,065 ERROR: Exception on /_response_email [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 251, in response_email
    send_response_email(email=recip,template=template)
  File "/Users/timc/PycharmProjects/SAAC/app/email.py", line 51, in send_response_email
    mail.send(msg)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'': (555, b'5.5.2 Syntax error. k38sm15986557qkh.72 - gsmtp')}
2018-11-04 14:56:46,812 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 10:06:32,843 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 10:09:01,229 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 10:10:19,982 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 10:12:19,601 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 12:11:20,103 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 12:12:57,196 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 12:13:34,955 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 12:13:37,240 ERROR: Exception on /unconfirmed [GET] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 117, in unconfirmed
    return redirect(url_for(account,name=current_user.name))
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/helpers.py", line 305, in url_for
    if endpoint[:1] == '.':
TypeError: 'function' object is not subscriptable
2018-11-05 12:47:06,423 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 13:11:09,439 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 13:12:08,455 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:01:10,716 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:09:08,713 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:10:07,709 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:16:12,443 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:16:42,402 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:16:56,933 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:21:26,957 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:22:32,622 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-05 17:23:44,198 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 13:32:57,547 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:31:19,079 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:41:37,256 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:43:48,771 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:47:07,505 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:51:06,604 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:54:06,639 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 14:57:30,339 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 18:50:28,426 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 18:52:02,780 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 18:59:53,357 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 18:59:58,610 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:00:07,586 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:01:40,483 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:01:44,048 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:01:51,284 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:01:58,041 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:02:57,179 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:03:01,777 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:03:09,368 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:04:47,441 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:24:48,202 INFO: Microblog startup [in /Users/timc/PycharmProjects/SAAC/app/__init__.py:47]
2018-11-06 19:25:56,503 ERROR: Exception on /_process [POST] [in /Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/timc/PycharmProjects/SAAC/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/timc/PycharmProjects/SAAC/app/routes.py", line 191, in process
    process_expertise_change(inputs)
  File "/Users/timc/PycharmProjects/SAAC/app/services.py", line 38, in process_expertise_change
    s.population += 1
AttributeError: 'Expertise' object has no attribute 'population'
